language: node_js

os:
  # - windows
  - linux
  - osx

node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"

script:
  - npm run codecov

cache:
  directories:
    - "node_modules"

notifications:
  email:
    on_success: never
    on_failure: always